export interface ComprehensiveSubject {
  id: string
  name: string
  category: string
  description: string
  icon: string
  color: string
  topics: ComprehensiveTopic[]
}

export interface ComprehensiveTopic {
  id: string
  name: string
  description: string
  difficulty_level: number
  estimated_cards: number
}

export const COMPREHENSIVE_SUBJECTS: ComprehensiveSubject[] = [
  // PRE-UNIVERSITY SUBJECTS
  {
    id: "matematica-pre",
    name: "Matemática (Pré-Vestibular)",
    category: "Pré-Universitário",
    description: "Matemática completa para vestibulares e ENEM",
    icon: "Calculator",
    color: "#3B82F6",
    topics: [
      {
        id: "algebra-basica",
        name: "Álgebra Básica",
        description: "Equações e inequações",
        difficulty_level: 2,
        estimated_cards: 15,
      },
      {
        id: "funcoes",
        name: "Funções",
        description: "Função afim, quadrática, exponencial, logarítmica",
        difficulty_level: 3,
        estimated_cards: 20,
      },
      {
        id: "geometria-plana",
        name: "Geometria Plana",
        description: "Áreas, perímetros, teoremas",
        difficulty_level: 3,
        estimated_cards: 18,
      },
      {
        id: "geometria-espacial",
        name: "Geometria Espacial",
        description: "Volumes e áreas de sólidos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "trigonometria",
        name: "Trigonometria",
        description: "Razões, identidades, equações",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "analise-combinatoria",
        name: "Análise Combinatória",
        description: "Permutações, arranjos, combinações",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "probabilidade",
        name: "Probabilidade",
        description: "Cálculo de probabilidades",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "estatistica-basica",
        name: "Estatística Básica",
        description: "Medidas de tendência central",
        difficulty_level: 2,
        estimated_cards: 8,
      },
      { id: "progressoes", name: "Progressões", description: "PA e PG", difficulty_level: 3, estimated_cards: 10 },
      {
        id: "matrizes-determinantes",
        name: "Matrizes e Determinantes",
        description: "Operações e aplicações",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "fisica-pre",
    name: "Física (Pré-Vestibular)",
    category: "Pré-Universitário",
    description: "Física completa para vestibulares",
    icon: "Zap",
    color: "#8B5CF6",
    topics: [
      {
        id: "cinematica",
        name: "Cinemática",
        description: "Movimento uniforme e variado",
        difficulty_level: 2,
        estimated_cards: 15,
      },
      {
        id: "dinamica",
        name: "Dinâmica",
        description: "Leis de Newton e aplicações",
        difficulty_level: 3,
        estimated_cards: 18,
      },
      {
        id: "energia-trabalho",
        name: "Energia e Trabalho",
        description: "Conservação de energia",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "hidrostática",
        name: "Hidrostática",
        description: "Pressão e empuxo",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "termologia",
        name: "Termologia",
        description: "Temperatura, calor, dilatação",
        difficulty_level: 3,
        estimated_cards: 16,
      },
      {
        id: "optica",
        name: "Óptica",
        description: "Reflexão, refração, lentes",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "eletrostatica",
        name: "Eletrostática",
        description: "Carga elétrica, campo elétrico",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "eletrodinamica",
        name: "Eletrodinâmica",
        description: "Corrente elétrica, circuitos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "magnetismo",
        name: "Magnetismo",
        description: "Campo magnético, indução",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "ondulatoria",
        name: "Ondulatória",
        description: "Ondas mecânicas e eletromagnéticas",
        difficulty_level: 4,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "quimica-pre",
    name: "Química (Pré-Vestibular)",
    category: "Pré-Universitário",
    description: "Química geral, orgânica e inorgânica",
    icon: "Flask",
    color: "#10B981",
    topics: [
      {
        id: "estrutura-atomica",
        name: "Estrutura Atômica",
        description: "Modelos atômicos, configuração eletrônica",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "tabela-periodica",
        name: "Tabela Periódica",
        description: "Propriedades periódicas",
        difficulty_level: 2,
        estimated_cards: 10,
      },
      {
        id: "ligacoes-quimicas",
        name: "Ligações Químicas",
        description: "Iônica, covalente, metálica",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "funcoes-inorganicas",
        name: "Funções Inorgânicas",
        description: "Ácidos, bases, sais, óxidos",
        difficulty_level: 2,
        estimated_cards: 16,
      },
      {
        id: "reacoes-quimicas",
        name: "Reações Químicas",
        description: "Balanceamento, tipos de reações",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "estequiometria",
        name: "Estequiometria",
        description: "Cálculos químicos",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "quimica-organica",
        name: "Química Orgânica",
        description: "Hidrocarbonetos, funções orgânicas",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "fisico-quimica",
        name: "Físico-Química",
        description: "Termoquímica, cinética, equilíbrio",
        difficulty_level: 5,
        estimated_cards: 16,
      },
    ],
  },
  {
    id: "biologia-pre",
    name: "Biologia (Pré-Vestibular)",
    category: "Pré-Universitário",
    description: "Biologia completa para vestibulares",
    icon: "Leaf",
    color: "#059669",
    topics: [
      {
        id: "citologia",
        name: "Citologia",
        description: "Estrutura e função celular",
        difficulty_level: 3,
        estimated_cards: 16,
      },
      {
        id: "histologia",
        name: "Histologia",
        description: "Tecidos animais e vegetais",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "fisiologia-humana",
        name: "Fisiologia Humana",
        description: "Sistemas do corpo humano",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "genetica",
        name: "Genética",
        description: "Leis de Mendel, hereditariedade",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "evolucao",
        name: "Evolução",
        description: "Teorias evolutivas, especiação",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "ecologia",
        name: "Ecologia",
        description: "Ecossistemas, relações ecológicas",
        difficulty_level: 3,
        estimated_cards: 16,
      },
      {
        id: "botanica",
        name: "Botânica",
        description: "Morfologia e fisiologia vegetal",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "zoologia",
        name: "Zoologia",
        description: "Classificação dos animais",
        difficulty_level: 3,
        estimated_cards: 12,
      },
    ],
  },

  // MEDICINE - Complete curriculum
  {
    id: "medicina-anatomia",
    name: "Anatomia Humana",
    category: "Medicina",
    description: "Anatomia sistêmica e regional",
    icon: "User",
    color: "#DC2626",
    topics: [
      {
        id: "sistema-musculoesqueletico",
        name: "Sistema Musculoesquelético",
        description: "Ossos, músculos, articulações",
        difficulty_level: 4,
        estimated_cards: 25,
      },
      {
        id: "sistema-cardiovascular",
        name: "Sistema Cardiovascular",
        description: "Coração, vasos sanguíneos",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "sistema-respiratorio",
        name: "Sistema Respiratório",
        description: "Vias aéreas, pulmões",
        difficulty_level: 3,
        estimated_cards: 15,
      },
      {
        id: "sistema-nervoso",
        name: "Sistema Nervoso",
        description: "SNC, SNP, neuroanatomia",
        difficulty_level: 5,
        estimated_cards: 30,
      },
      {
        id: "sistema-digestorio",
        name: "Sistema Digestório",
        description: "TGI, glândulas anexas",
        difficulty_level: 3,
        estimated_cards: 18,
      },
      {
        id: "sistema-geniturinario",
        name: "Sistema Geniturinário",
        description: "Rins, bexiga, órgãos reprodutivos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "cabeca-pescoco",
        name: "Cabeça e Pescoço",
        description: "Anatomia regional",
        difficulty_level: 5,
        estimated_cards: 22,
      },
      {
        id: "sistema-endocrino",
        name: "Sistema Endócrino",
        description: "Glândulas e hormônios",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "sistema-tegumentar",
        name: "Sistema Tegumentar",
        description: "Pele e anexos",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "anatomia-radiologica",
        name: "Anatomia Radiológica",
        description: "Anatomia em exames de imagem",
        difficulty_level: 5,
        estimated_cards: 18,
      },
    ],
  },
  {
    id: "medicina-fisiologia",
    name: "Fisiologia",
    category: "Medicina",
    description: "Funcionamento dos sistemas corporais",
    icon: "Activity",
    color: "#DC2626",
    topics: [
      {
        id: "fisiologia-cardiovascular",
        name: "Fisiologia Cardiovascular",
        description: "Função cardíaca, circulação",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "fisiologia-respiratoria",
        name: "Fisiologia Respiratória",
        description: "Ventilação, trocas gasosas",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "fisiologia-renal",
        name: "Fisiologia Renal",
        description: "Filtração, regulação hidroeletrolítica",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "neurofisiologia",
        name: "Neurofisiologia",
        description: "Função neural, transmissão sináptica",
        difficulty_level: 5,
        estimated_cards: 22,
      },
      {
        id: "endocrinologia",
        name: "Endocrinologia",
        description: "Hormônios, regulação metabólica",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "fisiologia-digestiva",
        name: "Fisiologia Digestiva",
        description: "Digestão, absorção",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "fisiologia-reprodutiva",
        name: "Fisiologia Reprodutiva",
        description: "Ciclos reprodutivos, fertilização",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "homeostase",
        name: "Homeostase",
        description: "Equilíbrio interno, regulação",
        difficulty_level: 4,
        estimated_cards: 15,
      },
    ],
  },
  {
    id: "medicina-bioquimica",
    name: "Bioquímica",
    category: "Medicina",
    description: "Processos químicos nos organismos vivos",
    icon: "Flask",
    color: "#DC2626",
    topics: [
      {
        id: "metabolismo-carboidratos",
        name: "Metabolismo de Carboidratos",
        description: "Glicólise, gliconeogênese, glicogenólise",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "metabolismo-lipidios",
        name: "Metabolismo de Lipídios",
        description: "Beta-oxidação, síntese de ácidos graxos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "metabolismo-proteinas",
        name: "Metabolismo de Proteínas",
        description: "Síntese e degradação proteica",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "enzimologia",
        name: "Enzimologia",
        description: "Cinética enzimática, regulação",
        difficulty_level: 5,
        estimated_cards: 20,
      },
      {
        id: "bioquimica-clinica",
        name: "Bioquímica Clínica",
        description: "Marcadores bioquímicos, diagnóstico",
        difficulty_level: 4,
        estimated_cards: 16,
      },
    ],
  },
  {
    id: "medicina-genetica",
    name: "Genética",
    category: "Medicina",
    description: "Hereditariedade e variação genética",
    icon: "Dna",
    color: "#DC2626",
    topics: [
      {
        id: "genetica-molecular",
        name: "Genética Molecular",
        description: "DNA, RNA, síntese proteica",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "genetica-medica",
        name: "Genética Médica",
        description: "Doenças genéticas, aconselhamento",
        difficulty_level: 5,
        estimated_cards: 20,
      },
      {
        id: "citogenetica",
        name: "Citogenética",
        description: "Cromossomos, aberrações cromossômicas",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "farmacogenetica",
        name: "Farmacogenética",
        description: "Genética e resposta a medicamentos",
        difficulty_level: 5,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "medicina-histologia",
    name: "Histologia",
    category: "Medicina",
    description: "Estudo dos tecidos",
    icon: "Microscope",
    color: "#DC2626",
    topics: [
      {
        id: "tecido-epitelial",
        name: "Tecido Epitelial",
        description: "Epitélios de revestimento e glandular",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "tecido-conjuntivo",
        name: "Tecido Conjuntivo",
        description: "Tecido conjuntivo propriamente dito",
        difficulty_level: 3,
        estimated_cards: 16,
      },
      {
        id: "tecido-muscular",
        name: "Tecido Muscular",
        description: "Músculo liso, estriado, cardíaco",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "tecido-nervoso",
        name: "Tecido Nervoso",
        description: "Neurônios, células da glia",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "tecido-hematopoetico",
        name: "Tecido Hematopoético",
        description: "Formação das células sanguíneas",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "medicina-embriologia",
    name: "Embriologia",
    category: "Medicina",
    description: "Desenvolvimento embrionário",
    icon: "Baby",
    color: "#DC2626",
    topics: [
      {
        id: "gametogenese",
        name: "Gametogênese",
        description: "Formação de gametas",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "fecundacao",
        name: "Fecundação",
        description: "Processo de fertilização",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "desenvolvimento-inicial",
        name: "Desenvolvimento Inicial",
        description: "Clivagem, gastrulação, neurulação",
        difficulty_level: 5,
        estimated_cards: 18,
      },
      {
        id: "organogenese",
        name: "Organogênese",
        description: "Formação dos órgãos",
        difficulty_level: 5,
        estimated_cards: 20,
      },
      {
        id: "malformacoes-congenitas",
        name: "Malformações Congênitas",
        description: "Defeitos do desenvolvimento",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "medicina-farmacologia",
    name: "Farmacologia",
    category: "Medicina",
    description: "Ação e efeitos dos medicamentos",
    icon: "Pill",
    color: "#DC2626",
    topics: [
      {
        id: "farmacocinetica",
        name: "Farmacocinética",
        description: "Absorção, distribuição, metabolismo, excreção",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "farmacodinamica",
        name: "Farmacodinâmica",
        description: "Mecanismos de ação dos fármacos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "farmacologia-cardiovascular",
        name: "Farmacologia Cardiovascular",
        description: "Medicamentos para o coração e vasos",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "farmacologia-snc",
        name: "Farmacologia do SNC",
        description: "Medicamentos neurológicos e psiquiátricos",
        difficulty_level: 5,
        estimated_cards: 22,
      },
      {
        id: "antibioticos",
        name: "Antibióticos",
        description: "Antimicrobianos e resistência",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "farmacologia-endocrina",
        name: "Farmacologia Endócrina",
        description: "Hormônios e medicamentos endócrinos",
        difficulty_level: 4,
        estimated_cards: 15,
      },
      {
        id: "toxicologia",
        name: "Toxicologia",
        description: "Efeitos tóxicos e intoxicações",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "medicina-microbiologia",
    name: "Microbiologia",
    category: "Medicina",
    description: "Estudo dos microrganismos",
    icon: "Bug",
    color: "#DC2626",
    topics: [
      {
        id: "bacteriologia",
        name: "Bacteriologia",
        description: "Bactérias patogênicas",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "virologia",
        name: "Virologia",
        description: "Vírus e infecções virais",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "micologia",
        name: "Micologia",
        description: "Fungos patogênicos",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "parasitologia",
        name: "Parasitologia",
        description: "Parasitas e parasitoses",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "microbiologia-clinica",
        name: "Microbiologia Clínica",
        description: "Diagnóstico microbiológico",
        difficulty_level: 4,
        estimated_cards: 15,
      },
    ],
  },
  {
    id: "medicina-imunologia",
    name: "Imunologia",
    category: "Medicina",
    description: "Sistema imunológico e defesas do organismo",
    icon: "Shield",
    color: "#DC2626",
    topics: [
      {
        id: "imunidade-inata",
        name: "Imunidade Inata",
        description: "Primeira linha de defesa",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "imunidade-adaptativa",
        name: "Imunidade Adaptativa",
        description: "Linfócitos T e B",
        difficulty_level: 5,
        estimated_cards: 18,
      },
      {
        id: "hipersensibilidade",
        name: "Hipersensibilidade",
        description: "Reações alérgicas",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "autoimunidade",
        name: "Autoimunidade",
        description: "Doenças autoimunes",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "imunodeficiencias",
        name: "Imunodeficiências",
        description: "Deficiências do sistema imune",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "medicina-patologia",
    name: "Patologia",
    category: "Medicina",
    description: "Mecanismos de doença",
    icon: "AlertTriangle",
    color: "#DC2626",
    topics: [
      {
        id: "inflamacao",
        name: "Inflamação",
        description: "Resposta inflamatória aguda e crônica",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "neoplasias",
        name: "Neoplasias",
        description: "Tumores benignos e malignos",
        difficulty_level: 5,
        estimated_cards: 20,
      },
      {
        id: "disturbios-circulatorios",
        name: "Distúrbios Circulatórios",
        description: "Trombose, embolia, isquemia",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "degeneracao-morte-celular",
        name: "Degeneração e Morte Celular",
        description: "Apoptose, necrose",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "cicatrizacao",
        name: "Cicatrização",
        description: "Reparo tecidual",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "patologia-genetica",
        name: "Patologia Genética",
        description: "Doenças hereditárias",
        difficulty_level: 5,
        estimated_cards: 15,
      },
      {
        id: "patologia-ambiental",
        name: "Patologia Ambiental",
        description: "Doenças por agentes externos",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "medicina-semiologia",
    name: "Semiologia Médica",
    category: "Medicina",
    description: "Exame clínico e diagnóstico",
    icon: "Stethoscope",
    color: "#DC2626",
    topics: [
      {
        id: "anamnese",
        name: "Anamnese",
        description: "História clínica do paciente",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "exame-fisico-geral",
        name: "Exame Físico Geral",
        description: "Inspeção, palpação, percussão, ausculta",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "semiologia-cardiovascular",
        name: "Semiologia Cardiovascular",
        description: "Exame do sistema cardiovascular",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "semiologia-respiratoria",
        name: "Semiologia Respiratória",
        description: "Exame do sistema respiratório",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "semiologia-neurologica",
        name: "Semiologia Neurológica",
        description: "Exame neurológico",
        difficulty_level: 5,
        estimated_cards: 20,
      },
    ],
  },
  {
    id: "medicina-clinica-medica",
    name: "Clínica Médica",
    category: "Medicina",
    description: "Diagnóstico e tratamento de doenças internas",
    icon: "Heart",
    color: "#DC2626",
    topics: [
      {
        id: "cardiologia-clinica",
        name: "Cardiologia Clínica",
        description: "Doenças cardiovasculares",
        difficulty_level: 5,
        estimated_cards: 22,
      },
      {
        id: "pneumologia-clinica",
        name: "Pneumologia Clínica",
        description: "Doenças respiratórias",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "gastroenterologia-clinica",
        name: "Gastroenterologia Clínica",
        description: "Doenças digestivas",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "endocrinologia-clinica",
        name: "Endocrinologia Clínica",
        description: "Doenças endócrinas",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "nefrologia-clinica",
        name: "Nefrologia Clínica",
        description: "Doenças renais",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },

  // DENTISTRY - Complete curriculum
  {
    id: "odontologia-anatomia",
    name: "Anatomia Dental",
    category: "Odontologia",
    description: "Anatomia dentária e estruturas orais",
    icon: "Smile",
    color: "#0891B2",
    topics: [
      {
        id: "anatomia-dental",
        name: "Anatomia Dental",
        description: "Morfologia dos dentes",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "anatomia-cabeca-pescoco",
        name: "Anatomia de Cabeça e Pescoço",
        description: "Estruturas oro-faciais",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      { id: "oclusao", name: "Oclusão", description: "Relações oclusais", difficulty_level: 4, estimated_cards: 14 },
      {
        id: "articulacao-temporomandibular",
        name: "ATM",
        description: "Articulação temporomandibular",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "anatomia-periodontal",
        name: "Anatomia Periodontal",
        description: "Estruturas de suporte dental",
        difficulty_level: 4,
        estimated_cards: 15,
      },
      {
        id: "anatomia-pulpar",
        name: "Anatomia Pulpar",
        description: "Sistema de canais radiculares",
        difficulty_level: 5,
        estimated_cards: 16,
      },
    ],
  },
  {
    id: "odontologia-patologia",
    name: "Patologia Bucal",
    category: "Odontologia",
    description: "Doenças da cavidade oral",
    icon: "AlertCircle",
    color: "#0891B2",
    topics: [
      {
        id: "lesoes-fundamentais",
        name: "Lesões Fundamentais",
        description: "Tipos básicos de lesões orais",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "patologia-pulpar",
        name: "Patologia Pulpar",
        description: "Doenças da polpa dental",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "patologia-periodontal",
        name: "Patologia Periodontal",
        description: "Doenças do periodonto",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "cistos-tumores",
        name: "Cistos e Tumores",
        description: "Lesões císticas e neoplásicas",
        difficulty_level: 5,
        estimated_cards: 18,
      },
      {
        id: "patologia-glandulas-salivares",
        name: "Patologia das Glândulas Salivares",
        description: "Doenças das glândulas salivares",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "manifestacoes-orais-doencas-sistemicas",
        name: "Manifestações Orais de Doenças Sistêmicas",
        description: "Sinais orais de doenças gerais",
        difficulty_level: 5,
        estimated_cards: 15,
      },
    ],
  },
  {
    id: "odontologia-radiologia",
    name: "Radiologia",
    category: "Odontologia",
    description: "Diagnóstico por imagem em odontologia",
    icon: "Scan",
    color: "#0891B2",
    topics: [
      {
        id: "tecnicas-radiograficas",
        name: "Técnicas Radiográficas",
        description: "Técnicas intra e extraorais",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "anatomia-radiografica",
        name: "Anatomia Radiográfica",
        description: "Estruturas normais em radiografias",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "patologia-radiografica",
        name: "Patologia Radiográfica",
        description: "Alterações patológicas em imagens",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "radioproteção",
        name: "Radioproteção",
        description: "Segurança radiológica",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "tomografia-computadorizada",
        name: "Tomografia Computadorizada",
        description: "TC cone beam em odontologia",
        difficulty_level: 5,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "odontologia-periodontia",
    name: "Periodontia",
    category: "Odontologia",
    description: "Tratamento das doenças periodontais",
    icon: "Heart",
    color: "#0891B2",
    topics: [
      {
        id: "anatomia-periodonto",
        name: "Anatomia do Periodonto",
        description: "Estruturas de suporte dental",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "doenca-periodontal",
        name: "Doença Periodontal",
        description: "Gengivite e periodontite",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "tratamento-periodontal",
        name: "Tratamento Periodontal",
        description: "Raspagem, alisamento, cirurgias",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "cirurgia-periodontal",
        name: "Cirurgia Periodontal",
        description: "Procedimentos cirúrgicos periodontais",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "implantodontia",
        name: "Implantodontia",
        description: "Implantes dentários",
        difficulty_level: 5,
        estimated_cards: 22,
      },
    ],
  },
  {
    id: "odontologia-dentistica",
    name: "Dentística",
    category: "Odontologia",
    description: "Restaurações dentárias",
    icon: "Wrench",
    color: "#0891B2",
    topics: [
      {
        id: "cariologia",
        name: "Cariologia",
        description: "Estudo da cárie dental",
        difficulty_level: 3,
        estimated_cards: 15,
      },
      {
        id: "materiais-restauradores",
        name: "Materiais Restauradores",
        description: "Resinas, amálgama, cerâmicas",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "preparos-cavitarios",
        name: "Preparos Cavitários",
        description: "Técnicas de preparo dental",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "estetica-dental",
        name: "Estética Dental",
        description: "Clareamento, facetas, laminados",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "adesao-dental",
        name: "Adesão Dental",
        description: "Sistemas adesivos",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "odontologia-endodontia",
    name: "Endodontia",
    category: "Odontologia",
    description: "Tratamento de canal",
    icon: "Zap",
    color: "#0891B2",
    topics: [
      {
        id: "diagnostico-endodontico",
        name: "Diagnóstico Endodôntico",
        description: "Testes de vitalidade pulpar",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "tratamento-endodontico",
        name: "Tratamento Endodôntico",
        description: "Técnicas de instrumentação",
        difficulty_level: 5,
        estimated_cards: 20,
      },
      {
        id: "medicacao-intracanal",
        name: "Medicação Intracanal",
        description: "Medicamentos endodônticos",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "obturacao-canais",
        name: "Obturação de Canais",
        description: "Técnicas de obturação",
        difficulty_level: 4,
        estimated_cards: 15,
      },
      {
        id: "retratamento-endodontico",
        name: "Retratamento Endodôntico",
        description: "Reintervenção endodôntica",
        difficulty_level: 5,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "odontologia-protese",
    name: "Prótese Dentária",
    category: "Odontologia",
    description: "Reabilitação protética",
    icon: "Settings",
    color: "#0891B2",
    topics: [
      {
        id: "protese-total",
        name: "Prótese Total",
        description: "Dentaduras completas",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "protese-parcial-removivel",
        name: "Prótese Parcial Removível",
        description: "PPR com grampos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "protese-fixa",
        name: "Prótese Fixa",
        description: "Coroas e pontes",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "protese-sobre-implantes",
        name: "Prótese sobre Implantes",
        description: "Reabilitação com implantes",
        difficulty_level: 5,
        estimated_cards: 18,
      },
      {
        id: "oclusao-protese",
        name: "Oclusão em Prótese",
        description: "Ajuste oclusal protético",
        difficulty_level: 5,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "odontologia-cirurgia",
    name: "Cirurgia Oral",
    category: "Odontologia",
    description: "Procedimentos cirúrgicos orais",
    icon: "Scissors",
    color: "#0891B2",
    topics: [
      {
        id: "exodontia",
        name: "Exodontia",
        description: "Extração dental",
        difficulty_level: 3,
        estimated_cards: 15,
      },
      {
        id: "cirurgia-terceiros-molares",
        name: "Cirurgia de Terceiros Molares",
        description: "Extração de sisos",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "cirurgia-pre-protética",
        name: "Cirurgia Pré-protética",
        description: "Preparação para próteses",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "traumatologia-bucomaxilofacial",
        name: "Traumatologia Bucomaxilofacial",
        description: "Fraturas faciais",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "anestesia-odontologica",
        name: "Anestesia Odontológica",
        description: "Técnicas anestésicas",
        difficulty_level: 3,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "odontologia-ortodontia",
    name: "Ortodontia",
    category: "Odontologia",
    description: "Correção da posição dos dentes",
    icon: "Smile",
    color: "#0891B2",
    topics: [
      {
        id: "crescimento-desenvolvimento",
        name: "Crescimento e Desenvolvimento",
        description: "Desenvolvimento craniofacial",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "diagnostico-ortodontico",
        name: "Diagnóstico Ortodôntico",
        description: "Análise cefalométrica, modelos",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "aparelhos-ortodonticos",
        name: "Aparelhos Ortodônticos",
        description: "Fixos, removíveis, funcionais",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "mecanica-ortodontica",
        name: "Mecânica Ortodôntica",
        description: "Forças, movimentos dentários",
        difficulty_level: 5,
        estimated_cards: 16,
      },
    ],
  },
  {
    id: "odontologia-odontopediatria",
    name: "Odontopediatria",
    category: "Odontologia",
    description: "Odontologia para crianças",
    icon: "Baby",
    color: "#0891B2",
    topics: [
      {
        id: "desenvolvimento-denticao",
        name: "Desenvolvimento da Dentição",
        description: "Cronologia de erupção",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "carie-infantil",
        name: "Cárie Infantil",
        description: "Prevenção e tratamento",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "traumatismo-dental-infantil",
        name: "Traumatismo Dental Infantil",
        description: "Manejo de traumas em dentes decíduos",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "comportamento-infantil",
        name: "Comportamento Infantil",
        description: "Manejo comportamental",
        difficulty_level: 3,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "odontologia-materiais",
    name: "Materiais Dentários",
    category: "Odontologia",
    description: "Propriedades dos materiais odontológicos",
    icon: "Layers",
    color: "#0891B2",
    topics: [
      {
        id: "propriedades-materiais",
        name: "Propriedades dos Materiais",
        description: "Físicas, químicas, mecânicas",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "materiais-restauradores-diretos",
        name: "Materiais Restauradores Diretos",
        description: "Resinas compostas, amálgama",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "materiais-protéticos",
        name: "Materiais Protéticos",
        description: "Cerâmicas, metais, polímeros",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "cimentos-dentarios",
        name: "Cimentos Dentários",
        description: "Ionômero de vidro, fosfato de zinco",
        difficulty_level: 3,
        estimated_cards: 12,
      },
    ],
  },

  // LAW - Complete curriculum
  {
    id: "direito-constitucional",
    name: "Direito Constitucional",
    category: "Direito",
    description: "Princípios e normas constitucionais",
    icon: "Scale",
    color: "#BE185D",
    topics: [
      {
        id: "principios-fundamentais",
        name: "Princípios Fundamentais",
        description: "Fundamentos do Estado brasileiro",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "direitos-garantias",
        name: "Direitos e Garantias Fundamentais",
        description: "Direitos individuais e coletivos",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "organizacao-estado",
        name: "Organização do Estado",
        description: "Federação, União, Estados, Municípios",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "poderes",
        name: "Organização dos Poderes",
        description: "Executivo, Legislativo, Judiciário",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "controle-constitucionalidade",
        name: "Controle de Constitucionalidade",
        description: "ADI, ADC, ADPF",
        difficulty_level: 5,
        estimated_cards: 14,
      },
      {
        id: "hermeneutica-constitucional",
        name: "Hermenêutica Constitucional",
        description: "Interpretação constitucional",
        difficulty_level: 5,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "direito-administrativo",
    name: "Direito Administrativo",
    category: "Direito",
    description: "Administração pública e atos administrativos",
    icon: "Building2",
    color: "#BE185D",
    topics: [
      {
        id: "principios-administrativos",
        name: "Princípios Administrativos",
        description: "LIMPE, supremacia, indisponibilidade",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "atos-administrativos",
        name: "Atos Administrativos",
        description: "Conceito, elementos, classificação",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "licitacoes",
        name: "Licitações",
        description: "Modalidades, procedimentos",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "contratos-administrativos",
        name: "Contratos Administrativos",
        description: "Características, cláusulas",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "servicos-publicos",
        name: "Serviços Públicos",
        description: "Concessão, permissão, autorização",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "responsabilidade-estado",
        name: "Responsabilidade do Estado",
        description: "Responsabilidade civil do Estado",
        difficulty_level: 4,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "direito-civil",
    name: "Direito Civil",
    category: "Direito",
    description: "Relações jurídicas entre particulares",
    icon: "Users",
    color: "#BE185D",
    topics: [
      {
        id: "parte-geral",
        name: "Parte Geral",
        description: "Pessoas, bens, fatos jurídicos",
        difficulty_level: 3,
        estimated_cards: 18,
      },
      {
        id: "obrigacoes",
        name: "Direito das Obrigações",
        description: "Contratos, responsabilidade civil",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "reais",
        name: "Direitos Reais",
        description: "Propriedade, posse, direitos reais",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "familia",
        name: "Direito de Família",
        description: "Casamento, união estável, filiação",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "sucessoes",
        name: "Direito das Sucessões",
        description: "Herança, testamento, inventário",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "responsabilidade-civil",
        name: "Responsabilidade Civil",
        description: "Dano moral, material, nexo causal",
        difficulty_level: 4,
        estimated_cards: 16,
      },
    ],
  },
  {
    id: "direito-penal",
    name: "Direito Penal",
    category: "Direito",
    description: "Crimes e punições",
    icon: "Shield",
    color: "#BE185D",
    topics: [
      {
        id: "teoria-geral-crime",
        name: "Teoria Geral do Crime",
        description: "Conceito, elementos, classificação",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "parte-especial",
        name: "Parte Especial",
        description: "Crimes em espécie",
        difficulty_level: 4,
        estimated_cards: 22,
      },
      {
        id: "penas",
        name: "Teoria da Pena",
        description: "Aplicação e execução das penas",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "concurso-crimes",
        name: "Concurso de Crimes",
        description: "Concurso material, formal, crime continuado",
        difficulty_level: 5,
        estimated_cards: 10,
      },
      {
        id: "crimes-contra-pessoa",
        name: "Crimes contra a Pessoa",
        description: "Homicídio, lesão corporal",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "crimes-patrimonio",
        name: "Crimes contra o Patrimônio",
        description: "Furto, roubo, estelionato",
        difficulty_level: 4,
        estimated_cards: 16,
      },
    ],
  },
  {
    id: "direito-empresarial",
    name: "Direito Empresarial",
    category: "Direito",
    description: "Atividade empresarial e sociedades",
    icon: "Building",
    color: "#BE185D",
    topics: [
      {
        id: "teoria-empresa",
        name: "Teoria da Empresa",
        description: "Conceito de empresário e empresa",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "sociedades-empresariais",
        name: "Sociedades Empresariais",
        description: "Tipos societários, constituição",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "titulos-credito",
        name: "Títulos de Crédito",
        description: "Cheque, nota promissória, duplicata",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "falencia-recuperacao",
        name: "Falência e Recuperação",
        description: "Insolvência empresarial",
        difficulty_level: 5,
        estimated_cards: 16,
      },
    ],
  },
  {
    id: "direito-trabalho",
    name: "Direito do Trabalho",
    category: "Direito",
    description: "Relações de trabalho e emprego",
    icon: "Briefcase",
    color: "#BE185D",
    topics: [
      {
        id: "contrato-trabalho",
        name: "Contrato de Trabalho",
        description: "Formação, elementos, modalidades",
        difficulty_level: 3,
        estimated_cards: 16,
      },
      {
        id: "jornada-trabalho",
        name: "Jornada de Trabalho",
        description: "Duração, horas extras, intervalos",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "salario-remuneracao",
        name: "Salário e Remuneração",
        description: "Conceitos, proteção salarial",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "extincao-contrato",
        name: "Extinção do Contrato",
        description: "Modalidades, verbas rescisórias",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "direito-coletivo",
        name: "Direito Coletivo do Trabalho",
        description: "Sindicatos, negociação coletiva",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "direito-tributario",
    name: "Direito Tributário",
    category: "Direito",
    description: "Sistema tributário nacional",
    icon: "Calculator",
    color: "#BE185D",
    topics: [
      {
        id: "sistema-tributario",
        name: "Sistema Tributário Nacional",
        description: "Competências tributárias",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "codigo-tributario",
        name: "Código Tributário Nacional",
        description: "Normas gerais tributárias",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "impostos-federais",
        name: "Impostos Federais",
        description: "IR, IPI, IOF, II, IE",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "impostos-estaduais",
        name: "Impostos Estaduais",
        description: "ICMS, IPVA, ITCMD",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "impostos-municipais",
        name: "Impostos Municipais",
        description: "IPTU, ISS, ITBI",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "processo-tributario",
        name: "Processo Tributário",
        description: "Lançamento, cobrança, execução fiscal",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "direito-processual-civil",
    name: "Direito Processual Civil",
    category: "Direito",
    description: "Processo civil e procedimentos",
    icon: "FileText",
    color: "#BE185D",
    topics: [
      {
        id: "teoria-geral-processo",
        name: "Teoria Geral do Processo",
        description: "Princípios processuais",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "procedimento-comum",
        name: "Procedimento Comum",
        description: "Petição inicial, contestação, sentença",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "recursos",
        name: "Recursos",
        description: "Apelação, agravo, embargos",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "execucao",
        name: "Execução",
        description: "Cumprimento de sentença",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "procedimentos-especiais",
        name: "Procedimentos Especiais",
        description: "Ações específicas",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "direito-processual-penal",
    name: "Direito Processual Penal",
    category: "Direito",
    description: "Processo penal e procedimentos criminais",
    icon: "Gavel",
    color: "#BE185D",
    topics: [
      {
        id: "inquerito-policial",
        name: "Inquérito Policial",
        description: "Investigação criminal",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "acao-penal",
        name: "Ação Penal",
        description: "Pública, privada, denúncia",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "prisoes-medidas-cautelares",
        name: "Prisões e Medidas Cautelares",
        description: "Prisão preventiva, temporária",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "procedimentos-penais",
        name: "Procedimentos Penais",
        description: "Comum, especiais, júri",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "recursos-penais",
        name: "Recursos Penais",
        description: "Apelação, recurso especial",
        difficulty_level: 5,
        estimated_cards: 14,
      },
    ],
  },

  // ENGINEERING - Complete curriculum
  {
    id: "engenharia-calculo",
    name: "Cálculo",
    category: "Engenharia",
    description: "Cálculo diferencial e integral aplicado",
    icon: "TrendingUp",
    color: "#7C3AED",
    topics: [
      {
        id: "limites-continuidade",
        name: "Limites e Continuidade",
        description: "Conceitos fundamentais",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "derivadas",
        name: "Derivadas",
        description: "Regras de derivação e aplicações",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "integrais",
        name: "Integrais",
        description: "Integração e aplicações",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "series",
        name: "Séries",
        description: "Séries infinitas e de potências",
        difficulty_level: 5,
        estimated_cards: 14,
      },
      {
        id: "equacoes-diferenciais",
        name: "Equações Diferenciais",
        description: "EDOs de primeira e segunda ordem",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "calculo-vetorial",
        name: "Cálculo Vetorial",
        description: "Gradiente, divergente, rotacional",
        difficulty_level: 5,
        estimated_cards: 18,
      },
      {
        id: "transformadas",
        name: "Transformadas",
        description: "Laplace, Fourier",
        difficulty_level: 5,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "engenharia-fisica",
    name: "Física",
    category: "Engenharia",
    description: "Física aplicada à engenharia",
    icon: "Atom",
    color: "#7C3AED",
    topics: [
      {
        id: "mecanica-classica",
        name: "Mecânica Clássica",
        description: "Dinâmica de partículas e corpos rígidos",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "termodinamica-eng",
        name: "Termodinâmica",
        description: "Leis da termodinâmica, ciclos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "eletromagnetismo-eng",
        name: "Eletromagnetismo",
        description: "Campos elétricos e magnéticos",
        difficulty_level: 5,
        estimated_cards: 18,
      },
      {
        id: "fisica-moderna",
        name: "Física Moderna",
        description: "Relatividade, mecânica quântica",
        difficulty_level: 5,
        estimated_cards: 14,
      },
      {
        id: "optica-eng",
        name: "Óptica",
        description: "Óptica geométrica e ondulatória",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "acustica",
        name: "Acústica",
        description: "Ondas sonoras e vibrações",
        difficulty_level: 4,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "engenharia-quimica",
    name: "Química",
    category: "Engenharia",
    description: "Química aplicada à engenharia",
    icon: "Flask",
    color: "#7C3AED",
    topics: [
      {
        id: "quimica-geral-eng",
        name: "Química Geral",
        description: "Estrutura atômica, ligações",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "quimica-organica-eng",
        name: "Química Orgânica",
        description: "Compostos orgânicos, reações",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "fisico-quimica-eng",
        name: "Físico-Química",
        description: "Termodinâmica química, cinética",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "quimica-analitica",
        name: "Química Analítica",
        description: "Métodos de análise",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "engenharia-desenho",
    name: "Desenho Técnico",
    category: "Engenharia",
    description: "Representação gráfica técnica",
    icon: "PenTool",
    color: "#7C3AED",
    topics: [
      {
        id: "projecoes-ortogonais",
        name: "Projeções Ortogonais",
        description: "Vistas principais, auxiliares",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "perspectiva-isometrica",
        name: "Perspectiva Isométrica",
        description: "Representação tridimensional",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "cortes-secoes",
        name: "Cortes e Seções",
        description: "Representação de detalhes internos",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "cotagem-tolerancias",
        name: "Cotagem e Tolerâncias",
        description: "Dimensionamento, ajustes",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "cad",
        name: "CAD",
        description: "Desenho assistido por computador",
        difficulty_level: 3,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "engenharia-materiais",
    name: "Ciência dos Materiais",
    category: "Engenharia",
    description: "Propriedades e comportamento dos materiais",
    icon: "Layers",
    color: "#7C3AED",
    topics: [
      {
        id: "estrutura-cristalina",
        name: "Estrutura Cristalina",
        description: "Arranjos atômicos em sólidos",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "propriedades-mecanicas",
        name: "Propriedades Mecânicas",
        description: "Resistência, dureza, tenacidade",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "diagramas-fase",
        name: "Diagramas de Fase",
        description: "Transformações de fase",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "corrosao",
        name: "Corrosão",
        description: "Degradação de materiais",
        difficulty_level: 3,
        estimated_cards: 10,
      },
      {
        id: "materiais-ceramicos",
        name: "Materiais Cerâmicos",
        description: "Cerâmicas técnicas e tradicionais",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "materiais-polimericos",
        name: "Materiais Poliméricos",
        description: "Plásticos e elastômeros",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "materiais-compositos",
        name: "Materiais Compósitos",
        description: "Fibras e matrizes",
        difficulty_level: 5,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "engenharia-mecanica-solidos",
    name: "Mecânica dos Sólidos",
    category: "Engenharia",
    description: "Análise de tensões e deformações",
    icon: "Box",
    color: "#7C3AED",
    topics: [
      {
        id: "estatica",
        name: "Estática",
        description: "Equilíbrio de corpos rígidos",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "resistencia-materiais",
        name: "Resistência dos Materiais",
        description: "Tensões, deformações, flexão",
        difficulty_level: 4,
        estimated_cards: 20,
      },
      {
        id: "dinamica-estrutural",
        name: "Dinâmica Estrutural",
        description: "Vibrações, análise modal",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "elementos-finitos",
        name: "Método dos Elementos Finitos",
        description: "Análise numérica de estruturas",
        difficulty_level: 5,
        estimated_cards: 14,
      },
    ],
  },

  // ADMINISTRATION - Complete curriculum
  {
    id: "administracao-estrategica",
    name: "Administração Estratégica",
    category: "Administração",
    description: "Planejamento e gestão estratégica",
    icon: "Target",
    color: "#F59E0B",
    topics: [
      {
        id: "planejamento-estrategico",
        name: "Planejamento Estratégico",
        description: "Missão, visão, objetivos estratégicos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "analise-ambiente",
        name: "Análise do Ambiente",
        description: "SWOT, Porter, cenários",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "estrategias-competitivas",
        name: "Estratégias Competitivas",
        description: "Diferenciação, liderança em custos",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "implementacao-estrategia",
        name: "Implementação da Estratégia",
        description: "Execução, controle estratégico",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "administracao-marketing",
    name: "Marketing",
    category: "Administração",
    description: "Estratégias de marketing e vendas",
    icon: "Megaphone",
    color: "#F59E0B",
    topics: [
      {
        id: "mix-marketing",
        name: "Mix de Marketing",
        description: "4Ps: produto, preço, praça, promoção",
        difficulty_level: 3,
        estimated_cards: 16,
      },
      {
        id: "comportamento-consumidor",
        name: "Comportamento do Consumidor",
        description: "Processo de compra, motivações",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "segmentacao-mercado",
        name: "Segmentação de Mercado",
        description: "Targeting, posicionamento",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "pesquisa-mercado",
        name: "Pesquisa de Mercado",
        description: "Métodos, análise de dados",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "marketing-digital",
        name: "Marketing Digital",
        description: "SEO, redes sociais, e-commerce",
        difficulty_level: 3,
        estimated_cards: 18,
      },
      {
        id: "branding",
        name: "Branding",
        description: "Gestão de marca, identidade",
        difficulty_level: 4,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "administracao-financas",
    name: "Finanças",
    category: "Administração",
    description: "Gestão financeira empresarial",
    icon: "DollarSign",
    color: "#F59E0B",
    topics: [
      {
        id: "analise-financeira",
        name: "Análise Financeira",
        description: "Índices, demonstrações",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "orcamento-capital",
        name: "Orçamento de Capital",
        description: "VPL, TIR, payback",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "estrutura-capital",
        name: "Estrutura de Capital",
        description: "Alavancagem, custo de capital",
        difficulty_level: 5,
        estimated_cards: 14,
      },
      {
        id: "gestao-capital-giro",
        name: "Gestão do Capital de Giro",
        description: "Fluxo de caixa, ciclo operacional",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "mercados-financeiros",
        name: "Mercados Financeiros",
        description: "Ações, títulos, derivativos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
    ],
  },
  {
    id: "administracao-rh",
    name: "Recursos Humanos",
    category: "Administração",
    description: "Gestão de pessoas",
    icon: "Users",
    color: "#F59E0B",
    topics: [
      {
        id: "recrutamento-selecao",
        name: "Recrutamento e Seleção",
        description: "Processos seletivos, entrevistas",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "treinamento-desenvolvimento",
        name: "Treinamento e Desenvolvimento",
        description: "Capacitação, educação corporativa",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "avaliacao-desempenho",
        name: "Avaliação de Desempenho",
        description: "Métodos, feedback, metas",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "remuneracao-beneficios",
        name: "Remuneração e Benefícios",
        description: "Salários, incentivos, benefícios",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "relacoes-trabalhistas",
        name: "Relações Trabalhistas",
        description: "CLT, sindicatos, negociações",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "clima-organizacional",
        name: "Clima Organizacional",
        description: "Cultura, motivação, satisfação",
        difficulty_level: 3,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "administracao-contabilidade",
    name: "Contabilidade",
    category: "Administração",
    description: "Contabilidade empresarial",
    icon: "Calculator",
    color: "#F59E0B",
    topics: [
      {
        id: "contabilidade-geral",
        name: "Contabilidade Geral",
        description: "Princípios, demonstrações contábeis",
        difficulty_level: 3,
        estimated_cards: 18,
      },
      {
        id: "contabilidade-custos",
        name: "Contabilidade de Custos",
        description: "Custeio, análise de custos",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "contabilidade-gerencial",
        name: "Contabilidade Gerencial",
        description: "Informações para tomada de decisão",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "auditoria",
        name: "Auditoria",
        description: "Auditoria interna e externa",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "administracao-economia",
    name: "Economia",
    category: "Administração",
    description: "Fundamentos econômicos",
    icon: "TrendingUp",
    color: "#F59E0B",
    topics: [
      {
        id: "microeconomia",
        name: "Microeconomia",
        description: "Oferta, demanda, elasticidade",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "macroeconomia",
        name: "Macroeconomia",
        description: "PIB, inflação, política monetária",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "economia-brasileira",
        name: "Economia Brasileira",
        description: "História econômica, planos",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "economia-internacional",
        name: "Economia Internacional",
        description: "Comércio exterior, câmbio",
        difficulty_level: 4,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "administracao-operacoes",
    name: "Operações",
    category: "Administração",
    description: "Gestão da produção e operações",
    icon: "Factory",
    color: "#F59E0B",
    topics: [
      {
        id: "planejamento-producao",
        name: "Planejamento da Produção",
        description: "PCP, capacidade, demanda",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "gestao-qualidade",
        name: "Gestão da Qualidade",
        description: "TQM, ISO, controle qualidade",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "gestao-estoques",
        name: "Gestão de Estoques",
        description: "Lote econômico, just-in-time",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "cadeia-suprimentos",
        name: "Cadeia de Suprimentos",
        description: "Logística, fornecedores",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "lean-manufacturing",
        name: "Lean Manufacturing",
        description: "Eliminação de desperdícios",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "administracao-empreendedorismo",
    name: "Empreendedorismo",
    category: "Administração",
    description: "Criação e gestão de novos negócios",
    icon: "Lightbulb",
    color: "#F59E0B",
    topics: [
      {
        id: "identificacao-oportunidades",
        name: "Identificação de Oportunidades",
        description: "Análise de mercado, inovação",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "plano-negocios",
        name: "Plano de Negócios",
        description: "Estrutura, viabilidade",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "financiamento-startups",
        name: "Financiamento de Startups",
        description: "Capital de risco, investidores",
        difficulty_level: 4,
        estimated_cards: 10,
      },
      {
        id: "gestao-inovacao",
        name: "Gestão da Inovação",
        description: "Processos inovativos",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },

  // PSYCHOLOGY - Complete curriculum
  {
    id: "psicologia-desenvolvimento",
    name: "Psicologia do Desenvolvimento",
    category: "Psicologia",
    description: "Desenvolvimento humano ao longo da vida",
    icon: "Baby",
    color: "#8B5CF6",
    topics: [
      {
        id: "desenvolvimento-cognitivo",
        name: "Desenvolvimento Cognitivo",
        description: "Piaget, Vygotsky, processamento",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "desenvolvimento-social",
        name: "Desenvolvimento Social",
        description: "Apego, socialização, identidade",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "desenvolvimento-moral",
        name: "Desenvolvimento Moral",
        description: "Kohlberg, julgamento moral",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "adolescencia",
        name: "Adolescência",
        description: "Mudanças físicas, psicológicas",
        difficulty_level: 3,
        estimated_cards: 14,
      },
      {
        id: "envelhecimento",
        name: "Envelhecimento",
        description: "Psicologia do idoso",
        difficulty_level: 3,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "psicologia-social",
    name: "Psicologia Social",
    category: "Psicologia",
    description: "Comportamento em contextos sociais",
    icon: "Users",
    color: "#8B5CF6",
    topics: [
      {
        id: "cognição-social",
        name: "Cognição Social",
        description: "Percepção social, atribuições",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "atitudes-persuasao",
        name: "Atitudes e Persuasão",
        description: "Formação, mudança de atitudes",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "grupos-lideranca",
        name: "Grupos e Liderança",
        description: "Dinâmica de grupos, liderança",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "preconceito-discriminacao",
        name: "Preconceito e Discriminação",
        description: "Estereótipos, relações intergrupais",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "comportamento-prosocial",
        name: "Comportamento Pró-social",
        description: "Altruísmo, cooperação",
        difficulty_level: 3,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "psicologia-psicopatologia",
    name: "Psicopatologia",
    category: "Psicologia",
    description: "Transtornos mentais e comportamentais",
    icon: "Brain",
    color: "#8B5CF6",
    topics: [
      {
        id: "transtornos-humor",
        name: "Transtornos do Humor",
        description: "Depressão, transtorno bipolar",
        difficulty_level: 5,
        estimated_cards: 18,
      },
      {
        id: "transtornos-ansiedade",
        name: "Transtornos de Ansiedade",
        description: "Fobias, pânico, ansiedade generalizada",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "transtornos-psicóticos",
        name: "Transtornos Psicóticos",
        description: "Esquizofrenia, delírios",
        difficulty_level: 5,
        estimated_cards: 14,
      },
      {
        id: "transtornos-personalidade",
        name: "Transtornos de Personalidade",
        description: "Borderline, narcisista, antissocial",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "transtornos-alimentares",
        name: "Transtornos Alimentares",
        description: "Anorexia, bulimia, compulsão",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "psicologia-personalidade",
    name: "Teorias da Personalidade",
    category: "Psicologia",
    description: "Teorias sobre a personalidade humana",
    icon: "User",
    color: "#8B5CF6",
    topics: [
      {
        id: "teoria-psicanalítica",
        name: "Teoria Psicanalítica",
        description: "Freud, Jung, estrutura da personalidade",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "teorias-humanistas",
        name: "Teorias Humanistas",
        description: "Rogers, Maslow, autorrealização",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "teorias-comportamentais",
        name: "Teorias Comportamentais",
        description: "Skinner, aprendizagem social",
        difficulty_level: 3,
        estimated_cards: 12,
      },
      {
        id: "teorias-cognitivas",
        name: "Teorias Cognitivas",
        description: "Kelly, Beck, esquemas cognitivos",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "big-five",
        name: "Modelo dos Cinco Fatores",
        description: "Big Five, traços de personalidade",
        difficulty_level: 3,
        estimated_cards: 10,
      },
    ],
  },
  {
    id: "psicologia-cognitiva",
    name: "Psicologia Cognitiva",
    category: "Psicologia",
    description: "Processos mentais e cognição",
    icon: "Brain",
    color: "#8B5CF6",
    topics: [
      {
        id: "percepcao",
        name: "Percepção",
        description: "Processamento sensorial, ilusões",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "atencao",
        name: "Atenção",
        description: "Seletiva, dividida, sustentada",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "memoria",
        name: "Memória",
        description: "Codificação, armazenamento, recuperação",
        difficulty_level: 4,
        estimated_cards: 18,
      },
      {
        id: "linguagem",
        name: "Linguagem",
        description: "Aquisição, processamento, produção",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "resolucao-problemas",
        name: "Resolução de Problemas",
        description: "Pensamento, criatividade, tomada de decisão",
        difficulty_level: 4,
        estimated_cards: 14,
      },
    ],
  },
  {
    id: "psicologia-neuropsicologia",
    name: "Neuropsicologia",
    category: "Psicologia",
    description: "Relação entre cérebro e comportamento",
    icon: "Brain",
    color: "#8B5CF6",
    topics: [
      {
        id: "neuroanatomia-funcional",
        name: "Neuroanatomia Funcional",
        description: "Estruturas cerebrais, funções",
        difficulty_level: 5,
        estimated_cards: 20,
      },
      {
        id: "lesoes-cerebrais",
        name: "Lesões Cerebrais",
        description: "AVC, traumatismo, consequências",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "avaliacao-neuropsicologica",
        name: "Avaliação Neuropsicológica",
        description: "Testes, bateria neuropsicológica",
        difficulty_level: 5,
        estimated_cards: 14,
      },
      {
        id: "reabilitacao-cognitiva",
        name: "Reabilitação Cognitiva",
        description: "Intervenções, recuperação",
        difficulty_level: 5,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "psicologia-clinica",
    name: "Psicologia Clínica",
    category: "Psicologia",
    description: "Prática clínica e psicoterapia",
    icon: "Heart",
    color: "#8B5CF6",
    topics: [
      {
        id: "avaliacao-psicologica",
        name: "Avaliação Psicológica",
        description: "Entrevista, testes, diagnóstico",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "psicoterapia-cognitiva",
        name: "Psicoterapia Cognitiva",
        description: "TCC, reestruturação cognitiva",
        difficulty_level: 5,
        estimated_cards: 18,
      },
      {
        id: "psicoterapia-humanista",
        name: "Psicoterapia Humanista",
        description: "Centrada na pessoa, Gestalt",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "psicoterapia-psicanalítica",
        name: "Psicoterapia Psicanalítica",
        description: "Transferência, interpretação",
        difficulty_level: 5,
        estimated_cards: 16,
      },
      {
        id: "terapia-familiar",
        name: "Terapia Familiar",
        description: "Sistêmica, dinâmica familiar",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
  {
    id: "psicologia-organizacional",
    name: "Psicologia Organizacional",
    category: "Psicologia",
    description: "Comportamento humano no trabalho",
    icon: "Building",
    color: "#8B5CF6",
    topics: [
      {
        id: "motivacao-trabalho",
        name: "Motivação no Trabalho",
        description: "Teorias motivacionais, engajamento",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "lideranca-organizacional",
        name: "Liderança Organizacional",
        description: "Estilos, eficácia, desenvolvimento",
        difficulty_level: 4,
        estimated_cards: 16,
      },
      {
        id: "cultura-organizacional",
        name: "Cultura Organizacional",
        description: "Valores, normas, mudança",
        difficulty_level: 4,
        estimated_cards: 12,
      },
      {
        id: "estresse-trabalho",
        name: "Estresse no Trabalho",
        description: "Burnout, coping, bem-estar",
        difficulty_level: 4,
        estimated_cards: 14,
      },
      {
        id: "selecao-pessoal",
        name: "Seleção de Pessoal",
        description: "Recrutamento, avaliação, predição",
        difficulty_level: 4,
        estimated_cards: 12,
      },
    ],
  },
]

export function getSubjectById(id: string): ComprehensiveSubject | undefined {
  return COMPREHENSIVE_SUBJECTS.find((subject) => subject.id === id)
}

export function getSubjectsByCategory(category: string): ComprehensiveSubject[] {
  return COMPREHENSIVE_SUBJECTS.filter((subject) => subject.category === category)
}

export function getAllCategories(): string[] {
  return [...new Set(COMPREHENSIVE_SUBJECTS.map((subject) => subject.category))]
}
