export interface ComprehensiveTopic {
  id: string
  name: string
  description: string
  estimated_cards: number
}

export interface ComprehensiveSubject {
  id: string
  name: string
  category: string
  description: string
  icon: string
  color: string
  topicCount: number
  totalEstimatedCards: number
  topics: ComprehensiveTopic[]
}

export const comprehensiveSubjectsData: { [category: string]: ComprehensiveSubject[] } = {
  "Ensino Médio": [
    {
      id: "matematica",
      name: "Matemática",
      category: "Ensino Médio",
      description: "Álgebra, Geometria, Cálculo e Estatística",
      icon: "Calculator",
      color: "#3B82F6",
      topicCount: 8,
      totalEstimatedCards: 120,
      topics: [
        { id: "algebra", name: "Álgebra", description: "Equações, funções e sistemas", estimated_cards: 20 },
        { id: "geometria", name: "Geometria", description: "Formas, áreas e volumes", estimated_cards: 18 },
        { id: "trigonometria", name: "Trigonometria", description: "Seno, cosseno e tangente", estimated_cards: 15 },
        {
          id: "estatistica",
          name: "Estatística",
          description: "Probabilidade e análise de dados",
          estimated_cards: 12,
        },
        { id: "calculo", name: "Cálculo", description: "Limites, derivadas e integrais", estimated_cards: 25 },
        {
          id: "matematica-financeira",
          name: "Matemática Financeira",
          description: "Juros, porcentagem e investimentos",
          estimated_cards: 10,
        },
        { id: "progressoes", name: "Progressões", description: "PA, PG e sequências", estimated_cards: 12 },
        { id: "matrizes", name: "Matrizes e Determinantes", description: "Operações matriciais", estimated_cards: 8 },
      ],
    },
    {
      id: "fisica",
      name: "Física",
      category: "Ensino Médio",
      description: "Mecânica, Termodinâmica, Eletromagnetismo e Óptica",
      icon: "Atom",
      color: "#10B981",
      topicCount: 6,
      totalEstimatedCards: 90,
      topics: [
        { id: "mecanica", name: "Mecânica", description: "Cinemática, dinâmica e estática", estimated_cards: 25 },
        { id: "termodinamica", name: "Termodinâmica", description: "Calor, temperatura e gases", estimated_cards: 15 },
        {
          id: "eletromagnetismo",
          name: "Eletromagnetismo",
          description: "Eletricidade e magnetismo",
          estimated_cards: 20,
        },
        { id: "optica", name: "Óptica", description: "Luz, reflexão e refração", estimated_cards: 12 },
        { id: "ondulatoria", name: "Ondulatória", description: "Ondas mecânicas e sonoras", estimated_cards: 10 },
        {
          id: "fisica-moderna",
          name: "Física Moderna",
          description: "Relatividade e física quântica",
          estimated_cards: 8,
        },
      ],
    },
    {
      id: "quimica",
      name: "Química",
      category: "Ensino Médio",
      description: "Química Geral, Orgânica e Inorgânica",
      icon: "Activity",
      color: "#8B5CF6",
      topicCount: 5,
      totalEstimatedCards: 75,
      topics: [
        { id: "quimica-geral", name: "Química Geral", description: "Átomos, ligações e reações", estimated_cards: 20 },
        { id: "quimica-organica", name: "Química Orgânica", description: "Compostos de carbono", estimated_cards: 18 },
        {
          id: "quimica-inorganica",
          name: "Química Inorgânica",
          description: "Ácidos, bases e sais",
          estimated_cards: 15,
        },
        { id: "fisico-quimica", name: "Físico-Química", description: "Termoquímica e cinética", estimated_cards: 12 },
        { id: "eletroquimica", name: "Eletroquímica", description: "Pilhas e eletrólise", estimated_cards: 10 },
      ],
    },
    {
      id: "biologia",
      name: "Biologia",
      category: "Ensino Médio",
      description: "Citologia, Genética, Ecologia e Evolução",
      icon: "Smile",
      color: "#059669",
      topicCount: 6,
      totalEstimatedCards: 80,
      topics: [
        { id: "citologia", name: "Citologia", description: "Estrutura e função celular", estimated_cards: 15 },
        { id: "genetica", name: "Genética", description: "Hereditariedade e DNA", estimated_cards: 18 },
        { id: "ecologia", name: "Ecologia", description: "Ecossistemas e meio ambiente", estimated_cards: 12 },
        { id: "evolucao", name: "Evolução", description: "Origem e evolução das espécies", estimated_cards: 10 },
        {
          id: "anatomia-fisiologia",
          name: "Anatomia e Fisiologia",
          description: "Sistemas do corpo humano",
          estimated_cards: 20,
        },
        { id: "botanica", name: "Botânica", description: "Reino vegetal", estimated_cards: 5 },
      ],
    },
    {
      id: "historia",
      name: "História",
      category: "Ensino Médio",
      description: "História do Brasil e História Geral",
      icon: "BookOpen",
      color: "#DC2626",
      topicCount: 4,
      totalEstimatedCards: 60,
      topics: [
        {
          id: "historia-brasil",
          name: "História do Brasil",
          description: "Colônia, Império e República",
          estimated_cards: 20,
        },
        {
          id: "historia-geral",
          name: "História Geral",
          description: "Antiguidade à Contemporaneidade",
          estimated_cards: 25,
        },
        {
          id: "historia-moderna",
          name: "História Moderna",
          description: "Renascimento ao Iluminismo",
          estimated_cards: 8,
        },
        {
          id: "historia-contemporanea",
          name: "História Contemporânea",
          description: "Século XIX aos dias atuais",
          estimated_cards: 7,
        },
      ],
    },
    {
      id: "geografia",
      name: "Geografia",
      category: "Ensino Médio",
      description: "Geografia Física e Humana",
      icon: "TrendingUp",
      color: "#0891B2",
      topicCount: 4,
      totalEstimatedCards: 50,
      topics: [
        {
          id: "geografia-fisica",
          name: "Geografia Física",
          description: "Relevo, clima e hidrografia",
          estimated_cards: 15,
        },
        {
          id: "geografia-humana",
          name: "Geografia Humana",
          description: "População e urbanização",
          estimated_cards: 12,
        },
        { id: "geopolitica", name: "Geopolítica", description: "Relações internacionais", estimated_cards: 10 },
        {
          id: "geografia-brasil",
          name: "Geografia do Brasil",
          description: "Regiões e características",
          estimated_cards: 13,
        },
      ],
    },
    {
      id: "portugues",
      name: "Língua Portuguesa",
      category: "Ensino Médio",
      description: "Gramática, Literatura e Redação",
      icon: "Users",
      color: "#7C3AED",
      topicCount: 4,
      totalEstimatedCards: 55,
      topics: [
        { id: "gramatica", name: "Gramática", description: "Sintaxe, morfologia e semântica", estimated_cards: 20 },
        { id: "literatura", name: "Literatura", description: "Escolas literárias e autores", estimated_cards: 15 },
        { id: "redacao", name: "Redação", description: "Técnicas de escrita e dissertação", estimated_cards: 12 },
        {
          id: "interpretacao",
          name: "Interpretação de Textos",
          description: "Compreensão e análise textual",
          estimated_cards: 8,
        },
      ],
    },
  ],
  "Ensino Superior": [
    {
      id: "medicina",
      name: "Medicina",
      category: "Ensino Superior",
      description: "Ciências médicas, diagnóstico e tratamento",
      icon: "User",
      color: "#DC2626",
      topicCount: 30,
      totalEstimatedCards: 450,
      topics: [
        {
          id: "anatomia-humana",
          name: "Anatomia Humana",
          description: "Estruturas do corpo humano",
          estimated_cards: 25,
        },
        {
          id: "fisiologia",
          name: "Fisiologia",
          description: "Funcionamento dos sistemas corporais",
          estimated_cards: 20,
        },
        {
          id: "bioquimica-medica",
          name: "Bioquímica",
          description: "Processos bioquímicos no organismo",
          estimated_cards: 18,
        },
        { id: "patologia", name: "Patologia", description: "Estudo das doenças", estimated_cards: 22 },
        {
          id: "farmacologia",
          name: "Farmacologia",
          description: "Ação e efeitos dos medicamentos",
          estimated_cards: 20,
        },
        { id: "microbiologia", name: "Microbiologia", description: "Microrganismos e infecções", estimated_cards: 15 },
        { id: "imunologia", name: "Imunologia", description: "Sistema imunológico e defesas", estimated_cards: 12 },
        { id: "cardiologia", name: "Cardiologia", description: "Doenças cardiovasculares", estimated_cards: 18 },
        { id: "neurologia", name: "Neurologia", description: "Sistema nervoso e distúrbios", estimated_cards: 16 },
        { id: "pediatria", name: "Pediatria", description: "Medicina infantil", estimated_cards: 14 },
        {
          id: "ginecologia-obstetricia",
          name: "Ginecologia e Obstetrícia",
          description: "Saúde da mulher e gravidez",
          estimated_cards: 16,
        },
        { id: "cirurgia", name: "Cirurgia", description: "Procedimentos cirúrgicos", estimated_cards: 20 },
        {
          id: "clinica-medica",
          name: "Clínica Médica",
          description: "Diagnóstico e tratamento clínico",
          estimated_cards: 18,
        },
        { id: "psiquiatria", name: "Psiquiatria", description: "Transtornos mentais", estimated_cards: 14 },
        { id: "dermatologia", name: "Dermatologia", description: "Doenças da pele", estimated_cards: 10 },
        { id: "oftalmologia", name: "Oftalmologia", description: "Doenças dos olhos", estimated_cards: 8 },
        {
          id: "otorrinolaringologia",
          name: "Otorrinolaringologia",
          description: "Ouvido, nariz e garganta",
          estimated_cards: 8,
        },
        { id: "ortopedia", name: "Ortopedia", description: "Sistema musculoesquelético", estimated_cards: 12 },
        { id: "urologia", name: "Urologia", description: "Sistema urinário", estimated_cards: 10 },
        { id: "gastroenterologia", name: "Gastroenterologia", description: "Sistema digestivo", estimated_cards: 12 },
        { id: "pneumologia", name: "Pneumologia", description: "Sistema respiratório", estimated_cards: 10 },
        {
          id: "endocrinologia",
          name: "Endocrinologia",
          description: "Sistema endócrino e hormônios",
          estimated_cards: 12,
        },
        { id: "nefrologia", name: "Nefrologia", description: "Doenças renais", estimated_cards: 10 },
        { id: "hematologia", name: "Hematologia", description: "Doenças do sangue", estimated_cards: 10 },
        { id: "oncologia", name: "Oncologia", description: "Câncer e tumores", estimated_cards: 15 },
        { id: "infectologia", name: "Infectologia", description: "Doenças infecciosas", estimated_cards: 12 },
        { id: "radiologia", name: "Radiologia", description: "Diagnóstico por imagem", estimated_cards: 10 },
        {
          id: "medicina-legal",
          name: "Medicina Legal",
          description: "Aspectos legais da medicina",
          estimated_cards: 8,
        },
        { id: "saude-publica", name: "Saúde Pública", description: "Epidemiologia e prevenção", estimated_cards: 12 },
        { id: "etica-medica", name: "Ética Médica", description: "Princípios éticos na medicina", estimated_cards: 8 },
      ],
    },
    {
      id: "direito",
      name: "Direito",
      category: "Ensino Superior",
      description: "Ciências jurídicas e sistema legal",
      icon: "Scale",
      color: "#1F2937",
      topicCount: 18,
      totalEstimatedCards: 270,
      topics: [
        {
          id: "direito-constitucional",
          name: "Direito Constitucional",
          description: "Constituição e direitos fundamentais",
          estimated_cards: 20,
        },
        {
          id: "direito-civil",
          name: "Direito Civil",
          description: "Relações privadas e contratos",
          estimated_cards: 25,
        },
        { id: "direito-penal", name: "Direito Penal", description: "Crimes e punições", estimated_cards: 22 },
        {
          id: "direito-processual-civil",
          name: "Direito Processual Civil",
          description: "Procedimentos judiciais cíveis",
          estimated_cards: 18,
        },
        {
          id: "direito-processual-penal",
          name: "Direito Processual Penal",
          description: "Procedimentos criminais",
          estimated_cards: 16,
        },
        {
          id: "direito-administrativo",
          name: "Direito Administrativo",
          description: "Administração pública",
          estimated_cards: 15,
        },
        {
          id: "direito-tributario",
          name: "Direito Tributário",
          description: "Impostos e tributos",
          estimated_cards: 14,
        },
        {
          id: "direito-trabalho",
          name: "Direito do Trabalho",
          description: "Relações trabalhistas",
          estimated_cards: 16,
        },
        {
          id: "direito-empresarial",
          name: "Direito Empresarial",
          description: "Atividade empresarial",
          estimated_cards: 12,
        },
        { id: "direito-ambiental", name: "Direito Ambiental", description: "Proteção ambiental", estimated_cards: 10 },
        {
          id: "direito-internacional-publico",
          name: "Direito Internacional Público",
          description: "Relações entre Estados",
          estimated_cards: 8,
        },
        {
          id: "direito-internacional-privado",
          name: "Direito Internacional Privado",
          description: "Conflitos de leis",
          estimated_cards: 8,
        },
        {
          id: "filosofia-direito",
          name: "Filosofia do Direito",
          description: "Fundamentos filosóficos",
          estimated_cards: 10,
        },
        {
          id: "teoria-direito",
          name: "Teoria do Direito",
          description: "Teoria geral do direito",
          estimated_cards: 12,
        },
        {
          id: "hermeneutica-juridica",
          name: "Hermenêutica Jurídica",
          description: "Interpretação das leis",
          estimated_cards: 8,
        },
        {
          id: "sociologia-juridica",
          name: "Sociologia Jurídica",
          description: "Direito e sociedade",
          estimated_cards: 8,
        },
        {
          id: "direito-previdenciario",
          name: "Direito Previdenciário",
          description: "Seguridade social",
          estimated_cards: 10,
        },
        { id: "direito-digital", name: "Direito Digital", description: "Tecnologia e direito", estimated_cards: 8 },
      ],
    },
    {
      id: "odontologia",
      name: "Odontologia",
      category: "Ensino Superior",
      description: "Saúde bucal e tratamentos dentários",
      icon: "Smile",
      color: "#0891B2",
      topicCount: 15,
      totalEstimatedCards: 225,
      topics: [
        {
          id: "anatomia-dental",
          name: "Anatomia Dental",
          description: "Estrutura dos dentes e boca",
          estimated_cards: 20,
        },
        {
          id: "anatomia-humana-odonto",
          name: "Anatomia Humana (Odonto)",
          description: "Anatomia aplicada à odontologia",
          estimated_cards: 15,
        },
        { id: "dentistica", name: "Dentística", description: "Restaurações dentárias", estimated_cards: 18 },
        { id: "endodontia", name: "Endodontia", description: "Tratamento de canal", estimated_cards: 16 },
        { id: "periodontia", name: "Periodontia", description: "Doenças da gengiva", estimated_cards: 14 },
        {
          id: "cirurgia-oral-menor",
          name: "Cirurgia Oral Menor",
          description: "Extrações e pequenas cirurgias",
          estimated_cards: 12,
        },
        {
          id: "cirurgia-oral-maior",
          name: "Cirurgia Oral Maior",
          description: "Cirurgias complexas",
          estimated_cards: 10,
        },
        { id: "ortodontia", name: "Ortodontia", description: "Correção de posição dentária", estimated_cards: 16 },
        { id: "protese-total", name: "Prótese Total", description: "Dentaduras completas", estimated_cards: 12 },
        { id: "protese-parcial", name: "Prótese Parcial", description: "Próteses removíveis", estimated_cards: 10 },
        { id: "odontopediatria", name: "Odontopediatria", description: "Odontologia infantil", estimated_cards: 12 },
        { id: "patologia-bucal", name: "Patologia Bucal", description: "Doenças da boca", estimated_cards: 14 },
        {
          id: "radiologia-odontologica",
          name: "Radiologia Odontológica",
          description: "Exames radiográficos",
          estimated_cards: 8,
        },
        {
          id: "materiais-dentarios",
          name: "Materiais Dentários",
          description: "Materiais usados em odontologia",
          estimated_cards: 10,
        },
        {
          id: "terapeutica-medicamentosa",
          name: "Terapêutica Medicamentosa",
          description: "Medicamentos em odontologia",
          estimated_cards: 8,
        },
      ],
    },
    {
      id: "engenharia",
      name: "Engenharia",
      category: "Ensino Superior",
      description: "Ciências exatas aplicadas e tecnologia",
      icon: "Code",
      color: "#7C3AED",
      topicCount: 16,
      totalEstimatedCards: 240,
      topics: [
        {
          id: "calculo-engenharia",
          name: "Cálculo (Engenharia)",
          description: "Cálculo diferencial e integral",
          estimated_cards: 20,
        },
        {
          id: "fisica-engenharia",
          name: "Física (Engenharia)",
          description: "Física aplicada à engenharia",
          estimated_cards: 18,
        },
        {
          id: "quimica-engenharia",
          name: "Química (Engenharia)",
          description: "Química para engenheiros",
          estimated_cards: 12,
        },
        {
          id: "desenho-tecnico",
          name: "Desenho Técnico",
          description: "Representação gráfica técnica",
          estimated_cards: 15,
        },
        {
          id: "mecanica-solidos",
          name: "Mecânica dos Sólidos",
          description: "Resistência dos materiais",
          estimated_cards: 16,
        },
        { id: "termodinamica-eng", name: "Termodinâmica", description: "Energia e calor", estimated_cards: 14 },
        {
          id: "eletromagnetismo-eng",
          name: "Eletromagnetismo",
          description: "Campos elétricos e magnéticos",
          estimated_cards: 12,
        },
        {
          id: "ciencia-materiais",
          name: "Ciência dos Materiais",
          description: "Propriedades dos materiais",
          estimated_cards: 14,
        },
        {
          id: "engenharia-civil",
          name: "Engenharia Civil",
          description: "Construção e infraestrutura",
          estimated_cards: 18,
        },
        {
          id: "engenharia-mecanica",
          name: "Engenharia Mecânica",
          description: "Máquinas e sistemas mecânicos",
          estimated_cards: 16,
        },
        {
          id: "engenharia-eletrica",
          name: "Engenharia Elétrica",
          description: "Sistemas elétricos",
          estimated_cards: 15,
        },
        {
          id: "engenharia-quimica",
          name: "Engenharia Química",
          description: "Processos químicos industriais",
          estimated_cards: 14,
        },
        {
          id: "engenharia-software",
          name: "Engenharia de Software",
          description: "Desenvolvimento de software",
          estimated_cards: 12,
        },
        {
          id: "engenharia-producao",
          name: "Engenharia de Produção",
          description: "Otimização de processos",
          estimated_cards: 10,
        },
        {
          id: "engenharia-ambiental",
          name: "Engenharia Ambiental",
          description: "Sustentabilidade e meio ambiente",
          estimated_cards: 8,
        },
        {
          id: "eletronica",
          name: "Eletrônica",
          description: "Circuitos e componentes eletrônicos",
          estimated_cards: 16,
        },
      ],
    },
    {
      id: "administracao",
      name: "Administração",
      category: "Ensino Superior",
      description: "Gestão empresarial e organizacional",
      icon: "TrendingUp",
      color: "#059669",
      topicCount: 11,
      totalEstimatedCards: 165,
      topics: [
        {
          id: "administracao-estrategica",
          name: "Administração Estratégica",
          description: "Planejamento e estratégia empresarial",
          estimated_cards: 18,
        },
        { id: "marketing", name: "Marketing", description: "Estratégias de mercado e vendas", estimated_cards: 16 },
        { id: "financas", name: "Finanças", description: "Gestão financeira empresarial", estimated_cards: 18 },
        { id: "recursos-humanos", name: "Recursos Humanos", description: "Gestão de pessoas", estimated_cards: 14 },
        { id: "operacoes", name: "Operações", description: "Gestão de operações e produção", estimated_cards: 12 },
        { id: "contabilidade", name: "Contabilidade", description: "Controle contábil e fiscal", estimated_cards: 16 },
        { id: "economia", name: "Economia", description: "Princípios econômicos", estimated_cards: 14 },
        {
          id: "estatistica-admin",
          name: "Estatística (Admin)",
          description: "Análise estatística empresarial",
          estimated_cards: 10,
        },
        {
          id: "comportamento-organizacional",
          name: "Comportamento Organizacional",
          description: "Psicologia organizacional",
          estimated_cards: 12,
        },
        {
          id: "empreendedorismo",
          name: "Empreendedorismo",
          description: "Criação e gestão de negócios",
          estimated_cards: 10,
        },
        {
          id: "direito-empresarial-admin",
          name: "Direito Empresarial (Admin)",
          description: "Aspectos legais empresariais",
          estimated_cards: 8,
        },
      ],
    },
    {
      id: "psicologia",
      name: "Psicologia",
      category: "Ensino Superior",
      description: "Comportamento humano e processos mentais",
      icon: "User",
      color: "#DC2626",
      topicCount: 10,
      totalEstimatedCards: 150,
      topics: [
        {
          id: "psicologia-geral",
          name: "Psicologia Geral",
          description: "Fundamentos da psicologia",
          estimated_cards: 18,
        },
        {
          id: "psicologia-desenvolvimento",
          name: "Psicologia do Desenvolvimento",
          description: "Desenvolvimento humano",
          estimated_cards: 16,
        },
        {
          id: "psicologia-social",
          name: "Psicologia Social",
          description: "Comportamento em grupos",
          estimated_cards: 14,
        },
        {
          id: "psicologia-cognitiva",
          name: "Psicologia Cognitiva",
          description: "Processos mentais e cognição",
          estimated_cards: 16,
        },
        {
          id: "psicologia-clinica",
          name: "Psicologia Clínica",
          description: "Diagnóstico e tratamento psicológico",
          estimated_cards: 18,
        },
        { id: "neuropsicologia", name: "Neuropsicologia", description: "Cérebro e comportamento", estimated_cards: 14 },
        { id: "psicopatologia", name: "Psicopatologia", description: "Transtornos mentais", estimated_cards: 16 },
        {
          id: "teorias-personalidade",
          name: "Teorias da Personalidade",
          description: "Estrutura da personalidade",
          estimated_cards: 12,
        },
        {
          id: "metodologia-pesquisa-psico",
          name: "Metodologia da Pesquisa (Psico)",
          description: "Métodos de pesquisa em psicologia",
          estimated_cards: 10,
        },
        {
          id: "estatistica-psico",
          name: "Estatística (Psico)",
          description: "Análise estatística em psicologia",
          estimated_cards: 8,
        },
      ],
    },
  ],
}

export const categories = Object.keys(comprehensiveSubjectsData)
