import { NextResponse } from "next/server"
import type { PrebuiltDeck } from "@/types/flashcards"
import { getAdminFlashcards } from "@/lib/admin-flashcard-store" // Importar store

// Comprehensive mock data for prebuilt decks
const mockPrebuiltDecks = [
  {
    id: "matematica-basica",
    name: "Matemática Básica - ENEM",
    description: "Fundamentos essenciais de matemática para o ENEM, incluindo álgebra, geometria e estatística básica.",
    subject_id: "matematica",
    category: "ENEM",
    difficulty_level: 2,
    total_cards: 25,
    estimated_time_minutes: 30,
    tags: ["enem", "matematica", "basico", "fundamental"],
    author_name: "Prof. Carlos Silva",
    is_featured: true,
    download_count: 1250,
    rating_average: 4.7,
    rating_count: 89,
    created_at: "2024-01-15T10:00:00Z",
    flashcard_subjects: {
      id: "matematica",
      name: "Matemática",
      category: "Exatas",
      color: "#2D7A18",
    },
  },
  {
    id: "fisica-mecanica",
    name: "Física - Mecânica Clássica",
    description: "Conceitos fundamentais de mecânica: cinemática, dinâmica, leis de Newton e aplicações práticas.",
    subject_id: "fisica",
    category: "Vestibular",
    difficulty_level: 3,
    total_cards: 30,
    estimated_time_minutes: 45,
    tags: ["fisica", "mecanica", "newton", "vestibular"],
    author_name: "Prof. Ana Santos",
    is_featured: true,
    download_count: 890,
    rating_average: 4.5,
    rating_count: 67,
    created_at: "2024-01-20T14:30:00Z",
    flashcard_subjects: {
      id: "fisica",
      name: "Física",
      category: "Exatas",
      color: "#1E40AF",
    },
  },
  {
    id: "quimica-organica-intro",
    name: "Introdução à Química Orgânica",
    description: "Fundamentos da química orgânica: hidrocarbonetos, grupos funcionais e reações básicas.",
    subject_id: "quimica",
    category: "Ensino Médio",
    difficulty_level: 3,
    total_cards: 35,
    estimated_time_minutes: 40,
    tags: ["quimica", "organica", "hidrocarbonetos", "funcoes"],
    author_name: "Prof. Roberto Lima",
    is_featured: false,
    download_count: 654,
    rating_average: 4.3,
    rating_count: 45,
    created_at: "2024-02-01T09:15:00Z",
    flashcard_subjects: {
      id: "quimica",
      name: "Química",
      category: "Exatas",
      color: "#059669",
    },
  },
  {
    id: "historia-brasil-colonial",
    name: "História do Brasil Colonial",
    description: "Período colonial brasileiro: descobrimento, colonização, economia açucareira e sociedade colonial.",
    subject_id: "historia",
    category: "História",
    difficulty_level: 2,
    total_cards: 28,
    estimated_time_minutes: 35,
    tags: ["historia", "brasil", "colonial", "descobrimento"],
    author_name: "Prof. Maria Oliveira",
    is_featured: true,
    download_count: 1100,
    rating_average: 4.6,
    rating_count: 78,
    created_at: "2024-01-25T16:45:00Z",
    flashcard_subjects: {
      id: "historia",
      name: "História",
      category: "Humanas",
      color: "#DC2626",
    },
  },
  {
    id: "geografia-brasil",
    name: "Geografia do Brasil",
    description:
      "Aspectos físicos, econômicos e sociais do território brasileiro: relevo, clima, população e economia.",
    subject_id: "geografia",
    category: "Geografia",
    difficulty_level: 2,
    total_cards: 32,
    estimated_time_minutes: 38,
    tags: ["geografia", "brasil", "relevo", "economia"],
    author_name: "Prof. João Costa",
    is_featured: false,
    download_count: 743,
    rating_average: 4.4,
    rating_count: 52,
    created_at: "2024-02-05T11:20:00Z",
    flashcard_subjects: {
      id: "geografia",
      name: "Geografia",
      category: "Humanas",
      color: "#7C2D12",
    },
  },
  {
    id: "portugues-gramatica",
    name: "Português - Gramática Essencial",
    description: "Conceitos fundamentais de gramática portuguesa: morfologia, sintaxe e análise sintática.",
    subject_id: "portugues",
    category: "Linguagens",
    difficulty_level: 3,
    total_cards: 40,
    estimated_time_minutes: 50,
    tags: ["portugues", "gramatica", "sintaxe", "morfologia"],
    author_name: "Prof. Lucia Ferreira",
    is_featured: true,
    download_count: 1350,
    rating_average: 4.8,
    rating_count: 95,
    created_at: "2024-01-18T13:10:00Z",
    flashcard_subjects: {
      id: "portugues",
      name: "Língua Portuguesa",
      category: "Linguagens",
      color: "#EA580C",
    },
  },
  {
    id: "biologia-citologia",
    name: "Biologia - Citologia",
    description: "Estrutura e função das células: organelas, membrana plasmática, núcleo e processos celulares.",
    subject_id: "biologia",
    category: "Biologia",
    difficulty_level: 3,
    total_cards: 33,
    estimated_time_minutes: 42,
    tags: ["biologia", "celula", "organelas", "citologia"],
    author_name: "Prof. Sandra Alves",
    is_featured: false,
    download_count: 567,
    rating_average: 4.2,
    rating_count: 38,
    created_at: "2024-02-08T15:30:00Z",
    flashcard_subjects: {
      id: "biologia",
      name: "Biologia",
      category: "Biológicas",
      color: "#16A34A",
    },
  },
  {
    id: "filosofia-antiga",
    name: "Filosofia Antiga",
    description:
      "Principais filósofos e conceitos da filosofia antiga: Sócrates, Platão, Aristóteles e pré-socráticos.",
    subject_id: "filosofia",
    category: "Filosofia",
    difficulty_level: 4,
    total_cards: 26,
    estimated_time_minutes: 35,
    tags: ["filosofia", "antiga", "socrates", "platao", "aristoteles"],
    author_name: "Prof. Eduardo Mendes",
    is_featured: false,
    download_count: 432,
    rating_average: 4.1,
    rating_count: 29,
    created_at: "2024-02-10T10:45:00Z",
    flashcard_subjects: {
      id: "filosofia",
      name: "Filosofia",
      category: "Humanas",
      color: "#7C3AED",
    },
  },
]

function createDeck(
  id: string,
  name: string,
  description: string,
  subjectInfo: { id: string; name: string; color: string },
  category: string,
  difficulty: number,
  cards: number,
  time: number,
  tags: string[],
  author: string,
  featured: boolean,
  downloads: number,
  rating: number,
  ratingCount: number,
): PrebuiltDeck {
  return {
    id,
    name,
    description,
    subject_id: subjectInfo.id,
    category,
    difficulty_level: difficulty,
    total_cards: cards,
    estimated_time_minutes: time,
    tags,
    author_name: author,
    is_featured: featured,
    download_count: downloads,
    rating_average: rating,
    rating_count: ratingCount,
    created_at: new Date().toISOString(),
    flashcard_subjects: {
      id: subjectInfo.id,
      name: subjectInfo.name,
      category: "Exatas", // This should be dynamic if subjects have categories
      color: subjectInfo.color,
    },
  }
}

function getMockPrebuiltDecks(): PrebuiltDeck[] {
  const subjects = {
    math: { id: "matematica", name: "Matemática", color: "#2D7A18" },
    physics: { id: "fisica", name: "Física", color: "#1E40AF" },
    chemistry: { id: "quimica", name: "Química", color: "#059669" },
    biology: { id: "biologia", name: "Biologia", color: "#16A34A" },
    history: { id: "historia", name: "História", color: "#DC2626" },
    geography: { id: "geografia", name: "Geografia", color: "#7C2D12" },
    portuguese: { id: "portugues", name: "Português", color: "#EA580C" },
    english: { id: "ingles", name: "Inglês", color: "#0891B2" },
    admin: { id: "admin-deck", name: "Admin", color: "#718096" },
  }

  const baseDecks: PrebuiltDeck[] = [
    createDeck(
      "matematica-basica",
      "Matemática Básica - ENEM",
      "Fundamentos essenciais de matemática para o ENEM, incluindo álgebra, geometria e estatística básica.",
      subjects.math,
      "ENEM",
      2,
      25,
      30,
      ["enem", "matematica", "basico", "fundamental"],
      "Prof. Carlos Silva",
      true,
      1250,
      4.7,
      89,
    ),
    createDeck(
      "fisica-mecanica",
      "Física - Mecânica Clássica",
      "Conceitos fundamentais de mecânica: cinemática, dinâmica, leis de Newton e aplicações práticas.",
      subjects.physics,
      "Vestibular",
      3,
      30,
      45,
      ["fisica", "mecanica", "newton", "vestibular"],
      "Prof. Ana Santos",
      true,
      890,
      4.5,
      67,
    ),
    createDeck(
      "quimica-organica-intro",
      "Introdução à Química Orgânica",
      "Fundamentos da química orgânica: hidrocarbonetos, grupos funcionais e reações básicas.",
      subjects.chemistry,
      "Ensino Médio",
      3,
      35,
      40,
      ["quimica", "organica", "hidrocarbonetos", "funcoes"],
      "Prof. Roberto Lima",
      false,
      654,
      4.3,
      45,
    ),
    createDeck(
      "historia-brasil-colonial",
      "História do Brasil Colonial",
      "Período colonial brasileiro: descobrimento, colonização, economia açucareira e sociedade colonial.",
      subjects.history,
      "História",
      2,
      28,
      35,
      ["historia", "brasil", "colonial", "descobrimento"],
      "Prof. Maria Oliveira",
      true,
      1100,
      4.6,
      78,
    ),
    createDeck(
      "geografia-brasil",
      "Geografia do Brasil",
      "Aspectos físicos, econômicos e sociais do território brasileiro: relevo, clima, população e economia.",
      subjects.geography,
      "Geografia",
      2,
      32,
      38,
      ["geografia", "brasil", "relevo", "economia"],
      "Prof. João Costa",
      false,
      743,
      4.4,
      52,
    ),
    createDeck(
      "portugues-gramatica",
      "Português - Gramática Essencial",
      "Conceitos fundamentais de gramática portuguesa: morfologia, sintaxe e análise sintática.",
      subjects.portuguese,
      "Linguagens",
      3,
      40,
      50,
      ["portugues", "gramatica", "sintaxe", "morfologia"],
      "Prof. Lucia Ferreira",
      true,
      1350,
      4.8,
      95,
    ),
    createDeck(
      "biologia-citologia",
      "Biologia - Citologia",
      "Estrutura e função das células: organelas, membrana plasmática, núcleo e processos celulares.",
      subjects.biology,
      "Biologia",
      3,
      33,
      42,
      ["biologia", "celula", "organelas", "citologia"],
      "Prof. Sandra Alves",
      false,
      567,
      4.2,
      38,
    ),
    createDeck(
      "filosofia-antiga",
      "Filosofia Antiga",
      "Principais filósofos e conceitos da filosofia antiga: Sócrates, Platão, Aristóteles e pré-socráticos.",
      subjects.admin,
      "Filosofia",
      4,
      26,
      35,
      ["filosofia", "antiga", "socrates", "platao", "aristoteles"],
      "Prof. Eduardo Mendes",
      false,
      432,
      4.1,
      29,
    ),
  ]

  const adminFlashcards = getAdminFlashcards()
  if (adminFlashcards.length > 0) {
    baseDecks.unshift(
      createDeck(
        "admin-created-deck",
        "Flashcards Criados pelo Admin",
        `Deck com ${adminFlashcards.length} flashcards adicionados recentemente.`,
        subjects.admin,
        "Admin",
        3,
        adminFlashcards.length,
        Math.ceil(adminFlashcards.length * 1.5),
        ["admin", "novos", "personalizado"],
        "Sistema Admin",
        true,
        0,
        0,
        0,
      ),
    )
  }

  return baseDecks
}

export async function GET() {
  try {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 300))

    const decks = getMockPrebuiltDecks()
    return NextResponse.json({
      success: true,
      decks: decks,
      total: decks.length,
    })
  } catch (error) {
    console.error("Error fetching prebuilt decks:", error)
    return NextResponse.json(
      {
        success: false,
        error: "Failed to fetch prebuilt decks",
        decks: [],
        total: 0,
      },
      { status: 500 },
    )
  }
}
