import { NextResponse } from "next/server"
import type { PrebuiltDeck } from "@/types/flashcards"

function createDeck(
  id: string,
  name: string,
  description: string,
  subjectInfo: { id: string; name: string; color: string },
  category: string,
  difficulty: number,
  cards: number,
  time: number,
  tags: string[],
  author: string,
  featured: boolean,
  downloads: number,
  rating: number,
  ratingCount: number,
): PrebuiltDeck {
  return {
    id,
    name,
    description,
    subject_id: subjectInfo.id,
    category,
    difficulty_level: difficulty,
    total_cards: cards,
    estimated_time_minutes: time,
    tags,
    author_name: author,
    is_featured: featured,
    download_count: downloads,
    rating_average: rating,
    rating_count: ratingCount,
    created_at: new Date().toISOString(),
    flashcard_subjects: {
      id: subjectInfo.id,
      name: subjectInfo.name,
      category: "Exatas", // This should be dynamic if subjects have categories
      color: subjectInfo.color,
    },
  }
}

function getMockPrebuiltDecks(): PrebuiltDeck[] {
  const subjects = {
    math: { id: "math", name: "Matemática", color: "#3B82F6" },
    physics: { id: "physics", name: "Física", color: "#10B981" },
    chemistry: { id: "chemistry", name: "Química", color: "#F59E0B" },
    biology: { id: "biology", name: "Biologia", color: "#EF4444" },
    history: { id: "history", name: "História", color: "#8B5CF6" },
    geography: { id: "geography", name: "Geografia", color: "#06B6D4" },
    portuguese: { id: "portuguese", name: "Português", color: "#EC4899" },
    english: { id: "english", name: "Inglês", color: "#F97316" },
  }

  return [
    createDeck(
      "deck-math-enem",
      "Matemática Essencial para ENEM",
      "Revise os tópicos de matemática mais cobrados no ENEM, de álgebra a geometria.",
      subjects.math,
      "featured",
      3,
      50,
      60,
      ["enem", "álgebra", "geometria", "matemática básica"],
      "Equipe Studify",
      true,
      1250,
      4.8,
      150,
    ),
    createDeck(
      "deck-physics-mechanics",
      "Física: Mecânica Completa",
      "Domine as Leis de Newton, cinemática, dinâmica e energia.",
      subjects.physics,
      "popular",
      4,
      40,
      50,
      ["física", "mecânica", "leis de newton", "vestibular"],
      "Prof. Newton",
      false,
      980,
      4.6,
      120,
    ),
    createDeck(
      "deck-chemistry-organic",
      "Química Orgânica Descomplicada",
      "Funções orgânicas, nomenclatura, isomeria e principais reações.",
      subjects.chemistry,
      "new",
      4,
      45,
      55,
      ["química orgânica", "funções", "reações", "carbono"],
      "Dra. Mendeleev",
      true,
      350,
      4.7,
      40,
    ),
    createDeck(
      "deck-biology-cytology",
      "Biologia Celular Detalhada",
      "Estrutura e função das organelas, metabolismo celular e divisão.",
      subjects.biology,
      "popular",
      3,
      35,
      45,
      ["biologia", "célula", "citologia", "organelas"],
      "BioExpert",
      false,
      1100,
      4.5,
      95,
    ),
    createDeck(
      "deck-history-brazil",
      "História do Brasil: Do Colonial à República",
      "Principais eventos e processos da formação histórica brasileira.",
      subjects.history,
      "featured",
      3,
      60,
      70,
      ["história do brasil", "colonial", "império", "república"],
      "Historiadores BR",
      true,
      1500,
      4.9,
      200,
    ),
    createDeck(
      "deck-geography-world",
      "Geografia Mundial: Continentes e Conflitos",
      "Explore a geopolítica, aspectos físicos e humanos dos continentes.",
      subjects.geography,
      "community",
      4,
      50,
      60,
      ["geografia", "mundo", "geopolítica", "continentes"],
      "GeoMappers",
      false,
      750,
      4.4,
      80,
    ),
    createDeck(
      "deck-portuguese-grammar",
      "Gramática Portuguesa para Concursos",
      "Regras gramaticais essenciais, sintaxe e morfologia para provas.",
      subjects.portuguese,
      "popular",
      4,
      55,
      65,
      ["português", "gramática", "concursos", "sintaxe"],
      "Prof. Pasquale",
      false,
      1300,
      4.7,
      180,
    ),
    createDeck(
      "deck-english-vocab",
      "Vocabulário Avançado em Inglês (ENEM/Vest.)",
      "Expanda seu vocabulário com termos frequentes em exames.",
      subjects.english,
      "new",
      3,
      100,
      40,
      ["inglês", "vocabulário", "enem", "ielts", "toefl"],
      "LinguaTech",
      false,
      600,
      4.6,
      70,
    ),
  ]
}

export async function GET() {
  // await new Promise(resolve => setTimeout(resolve, 500));
  // if (Math.random() < 0.1) {
  //   return NextResponse.json({ error: "Falha simulada ao buscar decks" }, { status: 500 });
  // }
  const decks = getMockPrebuiltDecks()
  return NextResponse.json({ decks })
}
